### ISSUE TITLE
Comment on each field

### ISSUE THREAD

**Issue by romainquellec** [membership/membership.db#12]
Hello.

Great project, but i'm not sure to get all the choices made for this db. (Working on postgresql)
Maybe, adding comments on each field can add a lot of values to this db.

Thanks again for this.

**Comment by romainquellec** [comment]
Look time no see. I'm closing this.

**Comment by vyuh** [comment]
Someone please tell the meaning of the columns of `user_claim` and `user_login` table. And maybe an example of how to use them for authentication/authorisation in an application.


Edit: I found some discussion on similar issue at https://gitter.im/membership/membership.db
