### ISSUE TITLE
Converting data to camel case for JSON

### ISSUE THREAD

**Issue by quantuminformation** [membership/membership.db#6]
Thanks for this great schema. Do you have some sort of utility for converting snake case results from postgresql node queries to camel case  to be sent to the client via JSON?

**Comment by koistya** [comment]
What platform, programming language you're targeting?

**Comment by quantuminformation** [comment]
node js + browser

**Comment by koistya** [comment]
Check out [this code snippet](https://coderwall.com/p/iprsng/convert-snake-case-to-camelcase) and tgriesser/knex#929

**Comment by quantuminformation** [comment]
Thanks
